version: "3"
services:
  golang: # exec golangでコンテナをたたける
    build:
      context: .
      dockerfile: ./build/Dockerfile
    # command: /bin/sh -c "go run ./cmd"
    tty: true
    ports:
      - 80:80
    volumes:
      - .:/go/src/app